### PR TITLE
Onboarding: update production suggested follows list

### PR DESCRIPTION
**Pull request by nvella**
Generated with this short Ruby script feeding in the CSV table exported directly from Notion
```ruby
require 'csv'
require 'yaml'

csv = CSV.new(STDIN, headers: true)

categories = csv.group_by {|row| row['Main Category']}.map do |category, accounts|
  {
    'name' => category,
    'accounts' => accounts.map {|row| row['Handle']}.to_a
  }
end.to_a

puts categories.to_yaml
```

(Yep, I was a Rubyist long ago—a very helpful coincidence with the Mastodon codebase 😆)

### CODE REVIEW

**Comment by felipecsl** [comment]
nice :) you'll need to run prettier, though, to make the linter happy. you can do that with:
```
yarn run prettier --write app/lib
```
and commit/push the changes

**Review by sdubinsky — APPROVED** [review]

**Comment by nvella** [comment]
No stress 👍 Linted and squashed into prev. commit

**Comment by felipecsl** [comment]
@sdubinsky don't forget to `ResolveAccountWorker.perform_async(handle)` these accounts in prod otherwise they won't show up in the API response, unless they have an `Account` record

**Comment by sdubinsky** [comment]
@felipecsl You mean just gotta do it once per account, and then we're good forever?

**Comment by felipecsl** [comment]
correct, once per account

**Comment by sdubinsky** [comment]
done

**Pull request merged**
