### PR TITLE
MAM-2712-make-foryou-status-update-worker-time-dynamtic

### PR DESCRIPTION
**Pull request by jtomchak**
* Set MAMMOTH_FOR_YOU_SCHEDULER to .env value with default `5`

### CODE REVIEW

**Review by rileyhCode — CHANGES_REQUESTED** [review]
I see MAMMOTH_FOR_YOU_SCHEDULER set to 10 in .env.production.sample, and to 5 in sidekiq.yml. Do you want to remove one of them?
If we make them match, is it possible we will change one, but not the other?

**Comment by jtomchak** [comment]
> I see MAMMOTH_FOR_YOU_SCHEDULER set to 10 in .env.production.sample, and to 5 in sidekiq.yml. Do you want to remove one of them?
> If we make them match, is it possible we will change one, but not the other?

in the sidekiq.yml file it's looking for the env MAMMOTH_FOR_YOU_SCHEDULER, and it `null` then it will use the default value of 5m

**Comment by jtomchak** [comment]
but you make a good point, future me it's gonna know that. Cleared up

**Review by rileyhCode — APPROVED** [review]
LGTM

**Pull request merged**
